# fly.toml app configuration file generated for sampel-app-rv on 2023-10-10T19:55:29-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sampel-app-rv"
primary_region = "yyz"
console_command = "/rails/bin/rails console"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
